### ISSUE TITLE
Self-contained workflow

### ISSUE THREAD

**Issue by jonocarroll** [timoast/notebook-template#2]
I love this. Using `bookdown` but running the new files individually is a great idea.

The shell script works as advertised, but I wonder if there's a reason it can't be done entirely within R? I'm happy to help build the functions to do these steps and expand this into a package, in the same spirit as https://github.com/knausb/labtools.

**Comment by timoast** [comment]
Hi! It would be awesome if you want to extend this stuff. It might be worth taking a look at blogdown though it you haven't already (https://bookdown.org/yihui/blogdown/; https://github.com/rstudio/blogdown), I have a feeling it's much better designed for being used as a notebook but I haven't had much time yet to check it out
